### ISSUE TITLE
Can't deploy.

### ISSUE THREAD

**Issue by srphcr** [r7kamura/fluct#32]
Maybe the response of AWS is changed.
So, the deployment will be failed with messages below.

``` node
TypeError: Cannot read property 'map' of undefined
    at NODE_PATH/lib/node_modules/fluct/node_modules/amazon-api-gateway-client/lib/client.js:303:25
    at runMicrotasksCallback (node.js:337:7)
    at process._tickDomainCallback (node.js:381:11)
```

I try to fix it, but little bit complicated...

**Comment by srphcr** [comment]
Change the target of this issue.
